---
- name: prepare zip
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Remove old file
      ansible.builtin.file:
        path: ~/Documents/GitHub/maxdevhd/mas-classes.zip
        state: absent
    - name: Create a zip archive
      community.general.archive:
        path: ~/Documents/GitHub/maxdevhd/*
        exclude_path:
        - ~/Documents/GitHub/maxdevhd/default.conf
        - ~/Documents/GitHub/maxdevhd/dockerfile
        - ~/Documents/GitHub/maxdevhd/my_server_block.conf
        - ~/Documents/GitHub/maxdevhd/prepare_archive.yml
        format: zip
        dest: ~/Documents/GitHub/maxdevhd/mas-classes.zip
    - name: build container image
      community.docker.docker_image:
         name: dhuberduda/nginx-mas
         build:
           path: ~/Documents/GitHub/maxdevhd/dockerfile
         source: build
         state: present
         push: true